- name: Install Packages
  yum:
    name:
      - haproxy
      - libselinux-python
      - libsemanage-python
    state: latest
  tags:
    - install-packages

- name: Copy haproxy.cfg Template
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
    setype: etc_t

- name: Enable haproxy_connect_any
  seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes

- name: Enable/Start haproxy Service
  systemd:
    name: haproxy
    state: restarted
    enabled: yes

- name: Enable proxied ports in firewall
  firewalld:
    port: "{{ item }}/tcp"
    state: enabled
    permanent: yes
    immediate: yes
  loop:
    - 80
    - 443
    - 6443
    - 22623
    - 9000
  tags:
    - firewalld