- name: Install DHCP Server Package
  yum:
    name:
      - dhcp
    state: latest

- name: Copy dhcpd.conf Template
  template:
    src: templates/dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: 0644
    setype: dhcp_etc_t

- name: Empty Leases File
  copy:
    content: ""
    dest: /var/lib/dhcpd/dhcpd.leases
    force: yes
    group: dhcpd
    mode: 0644
    owner: dhcpd
    serole: object_r
    setype: dhcpd_state_t
    seuser: system_u

- name: Enable/Start dhcpd Service
  systemd:
    name: dhcpd
    state: restarted
    enabled: yes
